name: my_way_home
description: A Flutter app to show traffic and stock info dashboard
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
